---
version: '3.8'
services:
  sampledb:
    image: postgres:13
    environment:
      POSTGRES_USER: sampledb
      POSTGRES_PASSWORD: sampledb
      POSTGRES_DB: sampledb
    volumes:
      - postgres-sampledb-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sampledb"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  postgres-sampledb-volume:
